services:
  backend:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    # ADD THIS SECTION ⬇️
    env_file:
      - .env-example

  frontend:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    command: streamlit run app/frontend/frontend.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - backend
    # ADD THIS SECTION IF FRONTEND NEEDS KEYS TOO ⬇️
    env_file:
      - .env-example